spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/music
    username: root
    hikari:
      password: root123456
  servlet:
    multipart:
      max-file-size: 15MB
      max-request-size: 20MB
mybatis:
  #标注mybatis配置文件的位置
  #config-location: classpath:mybatis-config.xml
  #标注待解析的mapper的xml文件位置
  mapper-locations: classpath:mapper/*.xml
  #标注实体类位置
  type-aliases-package: com.music.pojo

server:
  port: 8080

